#!/usr/bin/env bash

param environment='local'

task test {
  echo 'Running tests'
}

task pack {
  mkdir -p ./.work/artifacts/
  tar -czf ./.work/artifacts/release.$RANDOM.tar.gz ./docker
}

task deploy {
  echo "Deploying to $environment using $DEPLOYMENT_KEY"
}
