#!/usr/bin/env bash

param environment='local'
param pipeline_counter=0

declare version="1.0.0.$pipeline_counter"

task test {
  echo 'Running tests'
}

task pack {
  mkdir -p ./.work/artifacts/
  tar -czf ./.work/artifacts/release.$version.tar.gz ./docker
}

task deploy {
  echo "Deploying release $version to $environment using $DEPLOYMENT_KEY"

  echo
  echo 'Listing files in artifacts dir'
  ls ./.work/artifacts/
}
